// Generated by tools/build-sw.mjs — do not edit by hand.
const CACHE = 'mwa-9c31f5ca42';
const FILES = ["./","index.html","manifest.webmanifest","lib/phaser.min.js","src/art/battlefield.js","src/art/creatures.js","src/art/fx.js","src/art/items.js","src/art/pets-a.js","src/art/pets-b.js","src/art/pets-c.js","src/art/pets-d.js","src/art/visuals.js","src/art/wizard.js","src/art/world.js","src/content/abilities.js","src/content/curriculum.js","src/content/grades/grade1.js","src/content/grades/grade2.js","src/content/grades/grade3.js","src/content/grades/grade4.js","src/content/grades/grade5.js","src/content/grades/grade6.js","src/content/items.js","src/content/lessons/grade1.js","src/content/lessons/grade2.js","src/content/lessons/grade3.js","src/content/lessons/grade4.js","src/content/lessons/grade5.js","src/content/lessons/grade6.js","src/content/lessons.js","src/content/mentalmath.js","src/content/qutil.js","src/content/species.js","src/content/world.js","src/core/adaptive.js","src/core/changelog.js","src/core/cloud.js","src/core/loadguard.js","src/core/music.js","src/core/rng.js","src/core/save.js","src/core/sfx.js","src/core/speech.js","src/core/telemetry.js","src/core/version.js","src/game/overworld.js","src/game/progress.js","src/game/scenery.js","src/main.js","src/ui/audiocontrol.js","src/ui/battle.js","src/ui/dom.js","src/ui/home.js","src/ui/hud.js","src/ui/lesson.js","src/ui/parent.js","src/ui/petinfo.js","src/ui/progressview.js","src/ui/question.js","src/ui/results.js","src/ui/sandbox.js","src/ui/sprint.js","src/ui/styles.css","src/ui/tutorial.js","src/ui/welcome.js","src/ui/whatsnew.js","icons/icon-180.png","icons/icon-192.png","icons/icon-512.png"];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request).then((res) => {
    if (res.ok && new URL(e.request.url).origin === location.origin) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); }
    return res;
  }).catch(() => caches.match('./index.html'))));
});
